package com.example.ahorcado;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

public class BaseDatos extends SQLiteOpenHelper {

    private final static String NAME = "ahorcado.db";
    private final static int VERSION = 1;
    private final static String ESPANIOL = "espaniol";
    private final static String INGLES = "ingles";
    private final static String DIFICULTAD = "dificultad";
    public final static int B1 = 1;
    public final static int B2 = 2;
    public final static int C1 = 3;

    public final static String VOCABULARIO = "Vocabulario";
    private final static String CREATE_VOCABULARIO = "CREATE TABLE " + VOCABULARIO + " (" +
                                                     " _id INTEGER PRIMARY KEY AUTOINCREMENT, " +
                                                     ESPANIOL + " TEXT, " +
                                                     INGLES + " TEXT, " +
                                                     DIFICULTAD +" INTEGER);";

    public BaseDatos(Context context){
        super(context, NAME, null, VERSION);
    }

    @Override
    public void onCreate(SQLiteDatabase database) {
        // Log.v(BaseDatos.class.getName(), "Creando Base de Datos");

        database.execSQL(CREATE_VOCABULARIO);

        // Base de datos inicial
        loadB1(database);
        // insertPalabra(database,"Perro","Dog",B1);
        // insertPalabra(database,"Casa","House",B1);
        // insertPalabra(database,"Gato","Cat",B1);

        // loadB2();
        insertPalabra(database,"Enfoque","Approach",B2);
        insertPalabra(database,"Ansioso","Eager",B2);
        insertPalabra(database,"Importante","Significant",B2);

        // loadC1();
        insertPalabra(database,"Descolorido","Faded",C1);
        insertPalabra(database,"Alacena","Larder",C1);
        insertPalabra(database,"Espolvorear","Sprinkle",C1);
    }

    private void insertPalabra(SQLiteDatabase database, String spa, String eng, int dif){
        database.execSQL("INSERT INTO "+VOCABULARIO+" ("+ESPANIOL+","+INGLES+","+DIFICULTAD+") " +
                         "VALUES ('" + spa + "', '" + eng + "', " + dif + ");");
    }

    private void doReset(SQLiteDatabase database){
        database.execSQL("DROP TABLE IF EXISTS " + VOCABULARIO);

        onCreate(database);
    }

    @Override
    public void onUpgrade(SQLiteDatabase database, int from, int to) {
        Log.v(BaseDatos.class.getName(), "Actualizando nueva version de la base de datos " + to  +
                                         ", eliminando datos");

        doReset(database);
    }

    public void insertPalabra(Palabra p) {
        SQLiteDatabase database = this.getWritableDatabase();

        /*
        database.execSQL("INSERT INTO Vocabulario (espaniol, ingles, dificultad) VALUES (" +
                         p.getEspaniol() + ", " + p.getIngles() + ", " + p.getDificultad() + ");";
        */

        ContentValues values = new ContentValues();

        values.put(ESPANIOL, p.getEspaniol());
        values.put(INGLES, p.getIngles());
        values.put(DIFICULTAD, p.getDificultad());

        if(database.insert(VOCABULARIO, null , values) == -1){
            database.close();
            throw new RuntimeException("No se ha podido insertar la palabra en la base de datos");
        }

        database.close();
    }

    public Palabra queryPalabraAleatoria() {

        Palabra palabra = null;

        SQLiteDatabase database = this.getReadableDatabase();

        String query = "SELECT * FROM " + VOCABULARIO +" ORDER BY RANDOM() LIMIT 1;";

        Cursor cursor = database.rawQuery(query, null);
        if(cursor.moveToFirst()){

            palabra = new Palabra(cursor.getString(cursor.getColumnIndex(ESPANIOL)),
                    cursor.getString(cursor.getColumnIndex(INGLES)),
                    cursor.getInt(cursor.getColumnIndex(DIFICULTAD)));
        }

        cursor.close();
        database.close();

        return palabra;
    }

    public Palabra queryPalabraAleatoria(int nivel, boolean acumulativo) {

        Palabra palabra = null;

        SQLiteDatabase database = this.getReadableDatabase();

        String query = "SELECT * FROM " + VOCABULARIO +
                " WHERE "+BaseDatos.DIFICULTAD + (acumulativo?"<=":"=") + nivel +
                " ORDER BY RANDOM() LIMIT 1;";

        Cursor cursor = database.rawQuery(query, null);
        if(cursor.moveToFirst()){

            palabra = new Palabra(cursor.getString(cursor.getColumnIndex(ESPANIOL)),
                    cursor.getString(cursor.getColumnIndex(INGLES)),
                    cursor.getInt(cursor.getColumnIndex(DIFICULTAD)));
        }

        cursor.close();
        database.close();

        return palabra;
    }

    /* ------------------------------------------------------------------------------------------ */
    /* - Carga de diccionarios de vocabulario a partir de las listas oficiales de Cambridge ----- */
    /* ------------------------------------------------------------------------------------------ */

    private void loadB1(SQLiteDatabase database) {
        insertPalabra(database, "acción", "action", B1);
        insertPalabra(database, "avión", "aeroplane", B1);
        insertPalabra(database, "aluminio", "aluminium", B1);
        insertPalabra(database, "cualquiera", "anybody", B1);
        insertPalabra(database, "artista", "artist", B1);
        insertPalabra(database, "escenario, de fondo", "background", B1);
        insertPalabra(database, "pájaro", "bird", B1);
        insertPalabra(database, "ciego", "blind", B1);
        insertPalabra(database, "rebotar", "bounce", B1);
        insertPalabra(database, "canal", "canal", B1);
        insertPalabra(database, "casete", "cassette", B1);
        insertPalabra(database, "siglo", "century", B1);
        insertPalabra(database, "circo", "circus", B1);
        insertPalabra(database, "empresa", "company", B1);
        insertPalabra(database, "composición", "composition", B1);
        insertPalabra(database, "algodón", "cotton", B1);
        insertPalabra(database, "cratividad", "creativity", B1);
        insertPalabra(database, "creador", "creator", B1);
        insertPalabra(database, "cilindro", "cylinder", B1);
        insertPalabra(database, "descripción", "description", B1);
        insertPalabra(database, "escritorio", "desk", B1);
        insertPalabra(database, "diagrama", "diagram", B1);
        insertPalabra(database, "diamante", "diamond", B1);
        insertPalabra(database, "desaparecer", "disappear", B1);
        insertPalabra(database, "disc jockey", "disc jockey", B1);
        insertPalabra(database, "disco", "disk", B1);
        insertPalabra(database, "Tierra", "Earth", B1);
        insertPalabra(database, "décimo octavo", "eighteenth", B1);
        insertPalabra(database, "motor", "engine", B1);
        insertPalabra(database, "experimento", "experiment", B1);
        insertPalabra(database, "factor", "factor", B1);
        insertPalabra(database, "fracaso", "failure", B1);
        insertPalabra(database, "papel de aluminio", "foil", B1);
        insertPalabra(database, "congelado", "frozen", B1);
        insertPalabra(database, "gramófono", "gramophone", B1);
        insertPalabra(database, "chicle", "chewing-gum", B1);
        insertPalabra(database, "hacer el pino", "handstand", B1);
        insertPalabra(database, "agujero", "hole", B1);
        insertPalabra(database, "impaciente", "impatient", B1);
        insertPalabra(database, "importante", "important", B1);
        insertPalabra(database, "innovación", "innovation", B1);
        insertPalabra(database, "inspiración", "inspiration", B1);
        insertPalabra(database, "inventar", "invent", B1);
        insertPalabra(database, "inventor", "inventor", B1);
        insertPalabra(database, "aterrizar", "land", B1);
        insertPalabra(database, "principalmente", "mainly", B1);
        insertPalabra(database, "mitad", "middle", B1);
        insertPalabra(database, "aguja", "needle", B1);
        insertPalabra(database, "diecinueve", "nineteenth", B1);
        insertPalabra(database, "darse cuenta", "notice", B1);
        insertPalabra(database, "objeto", "object", B1);
        insertPalabra(database, "abrir", "open", B1);
        insertPalabra(database, "fonógrafo", "phonograph", B1);
        insertPalabra(database, "piano", "piano", B1);
        insertPalabra(database, "planeta", "planet", B1);
        insertPalabra(database, "portátil", "portable", B1);
        insertPalabra(database, "práctica", "practice", B1);
        insertPalabra(database, "practicar", "practise", B1);
        insertPalabra(database, "programar", "program", B1);
        insertPalabra(database, "recibir", "receive", B1);
        insertPalabra(database, "grabación", "recording", B1);
        insertPalabra(database, "sonar, toca", "ring", B1);
        insertPalabra(database, "caucho, hule", "rubber", B1);
        insertPalabra(database, "red de seguridad", "safety net", B1);
        insertPalabra(database, "secretario", "secretary", B1);
        insertPalabra(database, "sentarse", "sit", B1);
        insertPalabra(database, "patín", "roller skate", B1);
        insertPalabra(database, "nave espacial", "spaceship", B1);
        insertPalabra(database, "especialista", "specialist", B1);
        insertPalabra(database, "paso", "step", B1);
        insertPalabra(database, "pegar", "stick", B1);
        insertPalabra(database, "sugerencia", "suggestion", B1);
        insertPalabra(database, "sistema", "system", B1);
        insertPalabra(database, "talento", "talent", B1);
        insertPalabra(database, "hacia", "towards", B1);
        insertPalabra(database, "trampolín", "trampoline", B1);
        insertPalabra(database, "trampa", "trap", B1);
        insertPalabra(database, "trapecio", "trapeze", B1);
        insertPalabra(database, "pantalones", "trousers", B1);
        insertPalabra(database, "verdad", "truth", B1);
        insertPalabra(database, "intentar", "try", B1);
        insertPalabra(database, "vigésimo", "twentieth", B1);
        insertPalabra(database, "neumático", "tyre", B1);
        insertPalabra(database, "único", "unique", B1);
        insertPalabra(database, "útil", "useful", B1);
        insertPalabra(database, "velcro", "velcro", B1);
        insertPalabra(database, "vinilo", "vinyl", B1);
        insertPalabra(database, "cera", "wax", B1);
        insertPalabra(database, "mojado", "wet", B1);
        insertPalabra(database, "inalámbrico", "wireless", B1);
        insertPalabra(database, "bosque", "woods", B1);
        insertPalabra(database, "tiro con arco", "archery", B1);
        insertPalabra(database, "atleta", "athlete", B1);
        insertPalabra(database, "mal", "badly", B1);
        insertPalabra(database, "baloncesto", "basketball", B1);
        insertPalabra(database, "tocar", "blow", B1);
        insertPalabra(database, "extraordinariamente", "brilliantly", B1);
        insertPalabra(database, "capitán", "captain", B1);
        insertPalabra(database, "campeón", "champion", B1);
        insertPalabra(database, "oportunidad", "chance", B1);
        insertPalabra(database, "claro", "clear", B1);
        insertPalabra(database, "¡felicidades!", "congratulations!", B1);
        insertPalabra(database, "costar", "cost", B1);
        insertPalabra(database, "curso", "course", B1);
        insertPalabra(database, "fantasear", "daydream", B1);
        insertPalabra(database, "dirección", "direction", B1);
        insertPalabra(database, "discapacidad", "disability", B1);
        insertPalabra(database, "discapacitado", "disabled", B1);
        insertPalabra(database, "disco", "discus", B1);
        insertPalabra(database, "distancia", "distance", B1);
        insertPalabra(database, "empate", "draw", B1);
        insertPalabra(database, "empatar", "draw", B1);
        insertPalabra(database, "más temprano", "earlier", B1);
        insertPalabra(database, "entusiasta", "enthusiastic", B1);
        insertPalabra(database, "el más rápido", "fastest", B1);
        insertPalabra(database, "olvidar", "forget", B1);
        insertPalabra(database, "soprenderse", "get a surprise", B1);
        insertPalabra(database, "ocurrirse una idea", "get an idea", B1);
        insertPalabra(database, "llegar a casa", "get home", B1);
        insertPalabra(database, "envejecer", "get old", B1);
        insertPalabra(database, "tener la respuesta", "get the answer", B1);
        insertPalabra(database, "mojarse", "get wet", B1);
        insertPalabra(database, "meta", "goal", B1);
        insertPalabra(database, "medalla de oro", "gold medal", B1);
        insertPalabra(database, "gruñón", "grumpy", B1);
        insertPalabra(database, "peluquero", "hairdresser", B1);
        insertPalabra(database, "felizmente", "happily", B1);
        insertPalabra(database, "duro", "hard", B1);
        insertPalabra(database, "él mismo", "himself", B1);
        insertPalabra(database, "honestamente", "honestly", B1);
        insertPalabra(database, "improvisar", "improvise", B1);
        insertPalabra(database, "herida", "injury", B1);
        insertPalabra(database, "jabalina", "javelin", B1);
        insertPalabra(database, "reír", "laugh", B1);
        insertPalabra(database, "aprender", "learn", B1);
        insertPalabra(database, "gustar", "like", B1);
        insertPalabra(database, "importar", "matter", B1);
        insertPalabra(database, "medallista", "medallist", B1);
        insertPalabra(database, "desordenado", "messy", B1);
        insertPalabra(database, "humor", "mood", B1);
        insertPalabra(database, "más ruidoso", "noisier", B1);
        insertPalabra(database, "ruidoso", "noisy", B1);
        insertPalabra(database, "normal", "ordinary", B1);
        insertPalabra(database, "orgulloso", "proud", B1);
        insertPalabra(database, "arbitro", "referee", B1);
        insertPalabra(database, "descansar", "rest", B1);
        insertPalabra(database, "correr", "run", B1);
        insertPalabra(database, "marcar", "score", B1);
        insertPalabra(database, "resultado", "score", B1);
        insertPalabra(database, "marcar un gol", "score a goal", B1);
        insertPalabra(database, "guión", "script", B1);
        insertPalabra(database, "mostrar", "show", B1);
        insertPalabra(database, "más lento", "slower", B1);
        insertPalabra(database, "sonreír", "smile", B1);
        insertPalabra(database, "antes", "sooner", B1);
        insertPalabra(database, "deportista", "sportspeople", B1);
        insertPalabra(database, "deportista", "sportsperson", B1);
        insertPalabra(database, "sprint", "sprint", B1);
        insertPalabra(database, "suponer", "suppose", B1);
        insertPalabra(database, "sorpresa", "surprise", B1);
        insertPalabra(database, "hablar", "talk", B1);
        insertPalabra(database, "equipo", "team", B1);
        insertPalabra(database, "lanzar", "throw", B1);
        insertPalabra(database, "más ordenado", "tidier", B1);
        insertPalabra(database, "silla de ruedas", "wheelchair", B1);
        insertPalabra(database, "silbido", "whistle", B1);
        insertPalabra(database, "taller", "workshop", B1);
        insertPalabra(database, "escribir", "write", B1);
        insertPalabra(database, "más joven", "younger", B1);
        insertPalabra(database, "acre", "acre", B1);
        insertPalabra(database, "además", "in addition", B1);
        insertPalabra(database, "objetivo", "aim", B1);
        insertPalabra(database, "ambiente", "atmosphere", B1);
        insertPalabra(database, "dormitorio", "bedroom", B1);
        insertPalabra(database, "bicicleta", "bicycle", B1);
        insertPalabra(database, "bici", "bike", B1);
        insertPalabra(database, "botella", "bottle", B1);
        insertPalabra(database, "boutique", "boutique", B1);
        insertPalabra(database, "respirar", "breathe", B1);
        insertPalabra(database, "gato", "cat", B1);
        insertPalabra(database, "causar", "cause", B1);
        insertPalabra(database, "seguridad", "certainty", B1);
        insertPalabra(database, "estribillo", "chorus", B1);
        insertPalabra(database, "cambio climático", "climate change", B1);
        insertPalabra(database, "ciclovía", "cycle lane", B1);
        insertPalabra(database, "diario", "daily", B1);
        insertPalabra(database, "dólar", "dollar", B1);
        insertPalabra(database, "espectacular", "dramatic", B1);
        insertPalabra(database, "tirar basura", "drop litter", B1);
        insertPalabra(database, "educación", "education", B1);
        insertPalabra(database, "entretenimiento", "entertainment", B1);
        insertPalabra(database, "medio ambiente", "environment", B1);
        insertPalabra(database, "medioambiental", "environmental", B1);
        insertPalabra(database, "gases (del tubo de escape)", "exhaust", B1);
        insertPalabra(database, "explicar", "explain", B1);
        insertPalabra(database, "fábrica", "factory", B1);
        insertPalabra(database, "suspender", "fail", B1);
        insertPalabra(database, "granjero", "farmer", B1);
        insertPalabra(database, "gases", "fumes", B1);
        insertPalabra(database, "calentamiento global", "global warming", B1);
        insertPalabra(database, "gris", "grey", B1);
        insertPalabra(database, "media hora", "half-hour", B1);
        insertPalabra(database, "más sano", "healthier", B1);
        insertPalabra(database, "mejorar", "improve", B1);
        insertPalabra(database, "aumentar", "increase", B1);
        insertPalabra(database, "viaje", "journey", B1);
        insertPalabra(database, "saber", "know", B1);
        insertPalabra(database, "más grande", "larger", B1);
        insertPalabra(database, "nivel", "level", B1);
        insertPalabra(database, "basura", "litter", B1);
        insertPalabra(database, "estacionamiento", "parking lot", B1);
        insertPalabra(database, "parcialmente", "partly", B1);
        insertPalabra(database, "recoger", "pick up", B1);
        insertPalabra(database, "rosa", "pink", B1);
        insertPalabra(database, "contaminar", "pollute", B1);
        insertPalabra(database, "contaminación", "pollution", B1);
        insertPalabra(database, "prometer", "promise", B1);
        insertPalabra(database, "precipitaciones", "rainfall", B1);
        insertPalabra(database, "selva tropical", "rainforest", B1);
        insertPalabra(database, "reciclar", "recycle", B1);
        insertPalabra(database, "reciclaje", "recycling", B1);
        insertPalabra(database, "reducir", "reduce", B1);
        insertPalabra(database, "devolver", "return", B1);
        insertPalabra(database, "aumentar", "rise", B1);
        insertPalabra(database, "basura", "rubbish", B1);
        insertPalabra(database, "plan", "scheme", B1);
        insertPalabra(database, "parecer", "seem", B1);
        insertPalabra(database, "esquí", "ski", B1);
        insertPalabra(database, "dar un portazo", "slam", B1);
        insertPalabra(database, "resolver", "solve", B1);
        insertPalabra(database, "pronto", "soon", B1);
        insertPalabra(database, "portavoz", "spokesman", B1);
        insertPalabra(database, "taxi", "taxi", B1);
        insertPalabra(database, "tráfico, tránsito", "traffic", B1);
        insertPalabra(database, "transporte", "transport", B1);
        insertPalabra(database, "a no ser que", "unless", B1);
        insertPalabra(database, "apartamento", "apartment", B1);
        insertPalabra(database, "preguntar", "ask", B1);
        insertPalabra(database, "béisbol", "baseball", B1);
        insertPalabra(database, "se supone que", "be supposed to do (sth)", B1);
        insertPalabra(database, "papelera", "bin", B1);
        insertPalabra(database, "galleta", "biscuit", B1);
        insertPalabra(database, "taxi", "cab", B1);
        insertPalabra(database, "gorra", "cap", B1);
        insertPalabra(database, "cobrar", "charge", B1);
        insertPalabra(database, "pista", "clue", B1);
        insertPalabra(database, "comentario", "comment", B1);
        insertPalabra(database, "centro", "downtown", B1);
        insertPalabra(database, "ascensor", "elevator", B1);
        insertPalabra(database, "extra", "extra", B1);
        insertPalabra(database, "apartamento", "flat", B1);
        insertPalabra(database, "basura", "garbage", B1);
        insertPalabra(database, "jardín", "garden", B1);
        insertPalabra(database, "gótico", "goth", B1);
        insertPalabra(database, "vacaciones", "holiday", B1);
        insertPalabra(database, "hogar", "home", B1);
        insertPalabra(database, "celoso", "jealous", B1);
        insertPalabra(database, "grande", "large", B1);
        insertPalabra(database, "ascensor", "lift", B1);
        insertPalabra(database, "red", "network", B1);
        insertPalabra(database, "con razón", "No wonder", B1);
        insertPalabra(database, "pantalones", "pants", B1);
        insertPalabra(database, "padre", "parent", B1);
        insertPalabra(database, "parque", "park", B1);
        insertPalabra(database, "acera", "pavement", B1);
        insertPalabra(database, "comentario", "post", B1);
        insertPalabra(database, "reacción", "reaction", B1);
        insertPalabra(database, "acera", "sidewalk", B1);
        insertPalabra(database, "cantante", "singer", B1);
        insertPalabra(database, "fútbol", "soccer", B1);
        insertPalabra(database, "tranvía", "streetcar", B1);
        insertPalabra(database, "enérgicamente", "strongly", B1);
        insertPalabra(database, "metro", "subway", B1);
        insertPalabra(database, "traje", "suit", B1);
        insertPalabra(database, "tatuaje", "tattoo", B1);
        insertPalabra(database, "corbata", "tie", B1);
        insertPalabra(database, "tranvía", "tram", B1);
        insertPalabra(database, "camión", "truck", B1);
        insertPalabra(database, "metro", "underground", B1);
        insertPalabra(database, "vacaciones", "vacation", B1);
        insertPalabra(database, "ay", "whoops!", B1);
        insertPalabra(database, "wi-fi", "wi-fi", B1);
        insertPalabra(database, "todavía", "yet", B1);
        insertPalabra(database, "cuenta", "account", B1);
        insertPalabra(database, "en realidad", "actually", B1);
        insertPalabra(database, "adulto", "adult ", B1);
        insertPalabra(database, "edad mínima", "age limit", B1);
        insertPalabra(database, "permitir", "allow", B1);
        insertPalabra(database, "zona", "area", B1);
        insertPalabra(database, "bebé", "baby", B1);
        insertPalabra(database, "espalda", "back", B1);
        insertPalabra(database, "bambú", "bamboo", B1);
        insertPalabra(database, "golpear", "beat", B1);
        insertPalabra(database, "tomar prestado", "borrow", B1);
        insertPalabra(database, "más valiente", "braver", B1);
        insertPalabra(database, "celebrar", "celebrate", B1);
        insertPalabra(database, "ceremonia", "ceremony", B1);
        insertPalabra(database, "certificado", "certificate", B1);
        insertPalabra(database, "pecho", "chest", B1);
        insertPalabra(database, "niño", "child", B1);
        insertPalabra(database, "ser mayor de edad", "come of age", B1);
        insertPalabra(database, "concierto", "concert", B1);
        insertPalabra(database, "pasillo", "corridor", B1);
        insertPalabra(database, "cocodrilo", "crocodile", B1);
        insertPalabra(database, "describir", "describe", B1);
        insertPalabra(database, "disfrazarse", "dress up", B1);
        insertPalabra(database, "mayor", "elderly", B1);
        insertPalabra(database, "entrar", "enter", B1);
        insertPalabra(database, "padre", "father", B1);
        insertPalabra(database, "festival", "festival", B1);
        insertPalabra(database, "bosque", "forest", B1);
        insertPalabra(database, "casarse", "get married", B1);
        insertPalabra(database, "planeador", "glider", B1);
        insertPalabra(database, "gobierno", "government", B1);
        insertPalabra(database, "castigar", "ground", B1);
        insertPalabra(database, "crecer, cultivar", "grow", B1);
        insertPalabra(database, "adulto", "grown-up", B1);
        insertPalabra(database, "quimono", "kimono", B1);
        insertPalabra(database, "cuchillo", "knife", B1);
        insertPalabra(database, "de la noche", "late-night", B1);
        insertPalabra(database, "dejar", "let", B1);
        insertPalabra(database, "límite", "limit", B1);
        insertPalabra(database, "maquillaje", "make-up", B1);
        insertPalabra(database, "de mediana edad", "middle-aged", B1);
        insertPalabra(database, "mínimo", "minimum", B1);
        insertPalabra(database, "festival de música", "music festival", B1);
        insertPalabra(database, "nido", "nest", B1);
        insertPalabra(database, "doloroso", "painful", B1);
        insertPalabra(database, "pensionado, jubilado", "pensioner", B1);
        insertPalabra(database, "permiso", "permission", B1);
        insertPalabra(database, "fotografiar", "photograph", B1);
        insertPalabra(database, "de correos", "postal", B1);
        insertPalabra(database, "preparar", "prepare", B1);
        insertPalabra(database, "responsabilidad", "responsibility", B1);
        insertPalabra(database, "cráneo", "skull", B1);
        insertPalabra(database, "fumar", "smoke", B1);
        insertPalabra(database, "discurso", "speech", B1);
        insertPalabra(database, "estadio", "stadium", B1);
        insertPalabra(database, "adolescente", "teenage", B1);
        insertPalabra(database, "adolescente", "teenager", B1);
        insertPalabra(database, "niño pequeño", "toddler", B1);
        insertPalabra(database, "antorcha", "torch", B1);
        insertPalabra(database, "tradicional", "traditional", B1);
        insertPalabra(database, "tribu", "tribe", B1);
        insertPalabra(database, "votar", "vote", B1);
        insertPalabra(database, "discusión", "argument", B1);
        insertPalabra(database, "sangre", "blood", B1);
        insertPalabra(database, "lata", "can", B1);
        insertPalabra(database, "importar", "care", B1);
        insertPalabra(database, "dinero en efectivo", "cash", B1);
        insertPalabra(database, "Navidad", "Christmas", B1);
        insertPalabra(database, "circulación sanguínea", "blood circulation", B1);
        insertPalabra(database, "cacao", "cocoa", B1);
        insertPalabra(database, "Coca Cola", "coke", B1);
        insertPalabra(database, "recoger", "collect", B1);
        insertPalabra(database, "cómodo", "comfortable", B1);
        insertPalabra(database, "quejarse", "complain", B1);
        insertPalabra(database, "esquina", "corner", B1);
        insertPalabra(database, "encantador", "delightful", B1);
        insertPalabra(database, "médico", "doctor", B1);
        insertPalabra(database, "exposición", "exhibition", B1);
        insertPalabra(database, "tonto", "fool", B1);
        insertPalabra(database, "parte delantera", "front", B1);
        insertPalabra(database, "fruncir el ceño", "frown", B1);
        insertPalabra(database, "diversión", "fun", B1);
        insertPalabra(database, "divertido", "funny", B1);
        insertPalabra(database, "contento", "glad", B1);
        insertPalabra(database, "odiar", "hate", B1);
        insertPalabra(database, "partirse de risa", "have a good laugh", B1);
        insertPalabra(database, "pasárselo bien", "have a good time", B1);
        insertPalabra(database, "divertirse", "have fun", B1);
        insertPalabra(database, "celebrar", "hold", B1);
        insertPalabra(database, "humor", "humour", B1);
        insertPalabra(database, "sistema inmunológico", "immune system", B1);
        insertPalabra(database, "chiste", "joke", B1);
        insertPalabra(database, "casero", "landlord", B1);
        insertPalabra(database, "risa", "laughter", B1);
        insertPalabra(database, "prestar", "lend", B1);
        insertPalabra(database, "echarse", "lie", B1);
        insertPalabra(database, "hacer el ridículo", "make a fool of yourself", B1);
        insertPalabra(database, "hacer una mueca", "make a funny face", B1);
        insertPalabra(database, "cometer un error", "make a mistake", B1);
        insertPalabra(database, "burlarse de alguien", "make fun of (sb)", B1);
        insertPalabra(database, "hacer reír a alguien", "make (sb) laugh", B1);
        insertPalabra(database, "material", "material", B1);
        insertPalabra(database, "medicina", "medicine", B1);
        insertPalabra(database, "malentendido", "misunderstanding", B1);
        insertPalabra(database, "mañana", "morning", B1);
        insertPalabra(database, "sin parar", "non-stop", B1);
        insertPalabra(database, "nariz", "nose", B1);
        insertPalabra(database, "nota", "note", B1);
        insertPalabra(database, "contrario", "opposite", B1);
        insertPalabra(database, "organización", "organisation", B1);
        insertPalabra(database, "libra", "pound", B1);
        insertPalabra(database, "cuestionario", "questionnaire", B1);
        insertPalabra(database, "recordar", "remind", B1);
        insertPalabra(database, "respuesta", "reply", B1);
        insertPalabra(database, "repaso", "revision", B1);
        insertPalabra(database, "rimar", "rhyme", B1);
        insertPalabra(database, "arena", "sand", B1);
        insertPalabra(database, "vender", "sell", B1);
        insertPalabra(database, "enviar", "send", B1);
        insertPalabra(database, "sentido del humor", "sense of humour", B1);
        insertPalabra(database, "señal", "sign", B1);
        insertPalabra(database, "cantar", "sing", B1);
        insertPalabra(database, "estresado", "stressed", B1);
        insertPalabra(database, "supermercado", "supermarket", B1);
        insertPalabra(database, "pensamiento", "thought", B1);
        insertPalabra(database, "preocuparse", "worry", B1);
        insertPalabra(database, "afectar", "affect", B1);
        insertPalabra(database, "después", "afterwards", B1);
        insertPalabra(database, "en total", "altogether", B1);
        insertPalabra(database, "animal", "animal", B1);
        insertPalabra(database, "plátano, banano", "banana", B1);
        insertPalabra(database, "comenzar", "begin", B1);
        insertPalabra(database, "bomba", "bomb", B1);
        insertPalabra(database, "traer", "bring", B1);
        insertPalabra(database, "quemar", "burn", B1);
        insertPalabra(database, "producto químico", "chemical", B1);
        insertPalabra(database, "cigarrillo", "cigarette", B1);
        insertPalabra(database, "aula", "classroom", B1);
        insertPalabra(database, "terminar", "complete", B1);
        insertPalabra(database, "confundir", "confuse", B1);
        insertPalabra(database, "consecuencia", "consequence", B1);
        insertPalabra(database, "dañar", "damage", B1);
        insertPalabra(database, "daño", "damage", B1);
        insertPalabra(database, "muerto", "dead", B1);
        insertPalabra(database, "muerte", "death", B1);
        insertPalabra(database, "desierto", "desert", B1);
        insertPalabra(database, "destruir", "destroy", B1);
        insertPalabra(database, "no estar de acuerdo", "disagree", B1);
        insertPalabra(database, "desastre", "disaster", B1);
        insertPalabra(database, "sueño", "dream", B1);
        insertPalabra(database, "seco", "dry", B1);
        insertPalabra(database, "terremoto", "earthquake", B1);
        insertPalabra(database, "emisión", "emission", B1);
        insertPalabra(database, "enorme", "enormous", B1);
        insertPalabra(database, "entrar en erupción", "erupt", B1);
        insertPalabra(database, "erupción", "eruption", B1);
        insertPalabra(database, "finalmente", "eventually", B1);
        insertPalabra(database, "granja", "farm", B1);
        insertPalabra(database, "temer", "fear", B1);
        insertPalabra(database, "menos", "fewer", B1);
        insertPalabra(database, "inundación", "flood", B1);
        insertPalabra(database, "gafas", "glasses", B1);
        insertPalabra(database, "gases de efecto invernadero", "greenhouse gas", B1);
        insertPalabra(database, "dañar", "harm", B1);
        insertPalabra(database, "daño", "harm", B1);
        insertPalabra(database, "cosecha", "harvest", B1);
        insertPalabra(database, "más alto", "higher", B1);
        insertPalabra(database, "hospital", "hospital", B1);
        insertPalabra(database, "humano", "human", B1);
        insertPalabra(database, "hambre", "hunger", B1);
        insertPalabra(database, "huracán", "hurricane", B1);
        insertPalabra(database, "imaginario", "imaginary", B1);
        insertPalabra(database, "inmigrante", "immigrant", B1);
        insertPalabra(database, "insecto", "insect", B1);
        insertPalabra(database, "kilómetro", "kilometre", B1);
        insertPalabra(database, "demoler", "knock down", B1);
        insertPalabra(database, "probable", "likely", B1);
        insertPalabra(database, "vivir", "live", B1);
        insertPalabra(database, "langosta", "locust", B1);
        insertPalabra(database, "más cercano", "nearest", B1);
        insertPalabra(database, "vecino", "neighbour", B1);
        insertPalabra(database, "noroeste", "northwest", B1);
        insertPalabra(database, "bomba nuclear", "nuclear bomb", B1);
        insertPalabra(database, "ofrecer", "offer", B1);
        insertPalabra(database, "gasolina", "petrol", B1);
        insertPalabra(database, "fuerte, poderoso", "powerful", B1);
        insertPalabra(database, "precio", "price", B1);
        insertPalabra(database, "proporción", "proportion", B1);
        insertPalabra(database, "recientemente", "recently", B1);
        insertPalabra(database, "negarse", "refuse", B1);
        insertPalabra(database, "rescatar", "rescue", B1);
        insertPalabra(database, "responsable", "responsible", B1);
        insertPalabra(database, "robar", "rob", B1);
        insertPalabra(database, "sal", "salt", B1);
        insertPalabra(database, "mar", "sea", B1);
        insertPalabra(database, "décimo séptimo", "seventeenth", B1);
        insertPalabra(database, "más pequeño", "smallest", B1);
        insertPalabra(database, "liso", "smooth", B1);
        insertPalabra(database, "fuente", "source", B1);
        insertPalabra(database, "robar", "steal", B1);
        insertPalabra(database, "enjambre", "swarm", B1);
        insertPalabra(database, "amenzar", "threaten", B1);
        insertPalabra(database, "diminuto", "tiny", B1);
        insertPalabra(database, "tsunami", "tsunami", B1);
        insertPalabra(database, "inhabitable", "uninhabitable", B1);
        insertPalabra(database, "molesto", "upset", B1);
        insertPalabra(database, "violento", "violent", B1);
        insertPalabra(database, "volcánico", "volcanic", B1);
        insertPalabra(database, "volcán", "volcano", B1);
        insertPalabra(database, "famoso", "well-known", B1);
        insertPalabra(database, "ancho", "wide", B1);
        insertPalabra(database, "antena", "aerial", B1);
        insertPalabra(database, "granero", "barn", B1);
        insertPalabra(database, "baño", "bathroom", B1);
        insertPalabra(database, "cama", "bed", B1);
        insertPalabra(database, "edificio de apartamentos", "block of flats", B1);
        insertPalabra(database, "reservar", "book ", B1);
        insertPalabra(database, "banda ancha", "broadband", B1);
        insertPalabra(database, "folleto", "brochure", B1);
        insertPalabra(database, "bungalow", "bungalow", B1);
        insertPalabra(database, "casa rodante", "caravan", B1);
        insertPalabra(database, "catástrofe", "catastrophe", B1);
        insertPalabra(database, "cueva", "cave", B1);
        insertPalabra(database, "encanto", "charm", B1);
        insertPalabra(database, "chimenea", "chimney", B1);
        insertPalabra(database, "conexión", "connection", B1);
        insertPalabra(database, "convertir", "convert", B1);
        insertPalabra(database, "cabaña", "cottage", B1);
        insertPalabra(database, "campo", "countryside", B1);
        insertPalabra(database, "vaca", "cow", B1);
        insertPalabra(database, "decisión", "decision", B1);
        insertPalabra(database, "no adosado", "detached house", B1);
        insertPalabra(database, "desacuerdo", "disagreement", B1);
        insertPalabra(database, "vivienda", "dwelling", B1);
        insertPalabra(database, "fundamental", "essential", B1);
        insertPalabra(database, "complejo, fraccionamiento", "estate", B1);
        insertPalabra(database, "explorar", "explore", B1);
        insertPalabra(database, "instalaciones", "facilities", B1);
        insertPalabra(database, "sentir", "feel", B1);
        insertPalabra(database, "valla", "fence", B1);
        insertPalabra(database, "garaje, cochera", "garage", B1);
        insertPalabra(database, "abuelo", "grandparent", B1);
        insertPalabra(database, "invitado", "guest", B1);
        insertPalabra(database, "colina", "hill", B1);
        insertPalabra(database, "hotel", "hotel", B1);
        insertPalabra(database, "complejo, fraccionamiento", "housing estate", B1);
        insertPalabra(database, "particular, individual", "individual", B1);
        insertPalabra(database, "herir", "injure", B1);
        insertPalabra(database, "jacuzzi", "jacuzzi", B1);
        insertPalabra(database, "vida", "lifetime", B1);
        insertPalabra(database, "lujoso", "luxurious", B1);
        insertPalabra(database, "ningún sitio", "nowhere", B1);
        insertPalabra(database, "tranquilo", "peaceful", B1);
        insertPalabra(database, "proporcionar", "provide", B1);
        insertPalabra(database, "habitación", "room", B1);
        insertPalabra(database, "casa semiadosada", "semi-detached house", B1);
        insertPalabra(database, "sudoroso", "sweaty", B1);
        insertPalabra(database, "temperatura", "temperature", B1);
        insertPalabra(database, "tienda de campaña, carpa", "tent", B1);
        insertPalabra(database, "casa adosada", "terraced house", B1);
        insertPalabra(database, "turista", "tourist", B1);
        insertPalabra(database, "aceptar", "accept", B1);
        insertPalabra(database, "ventaja", "advantage", B1);
        insertPalabra(database, "anuncio", "advertisement", B1);
        insertPalabra(database, "arquitecto", "architect", B1);
        insertPalabra(database, "bachillerato", "baccalaureate", B1);
        insertPalabra(database, "hora de acostarse", "bedtime", B1);
        insertPalabra(database, "cerebro", "brain", B1);
        insertPalabra(database, "navegar", "browse", B1);
        insertPalabra(database, "gráfico", "chart", B1);
        insertPalabra(database, "concentrarse", "concentrate", B1);
        insertPalabra(database, "país", "country", B1);
        insertPalabra(database, "hija", "daughter", B1);
        insertPalabra(database, "retrasar", "delay", B1);
        insertPalabra(database, "diseñar", "design", B1);
        insertPalabra(database, "plano", "design", B1);
        insertPalabra(database, "diferencia", "difference", B1);
        insertPalabra(database, "desventaja", "disadvantage", B1);
        insertPalabra(database, "experto", "expert", B1);
        insertPalabra(database, "justo", "fair", B1);
        insertPalabra(database, "hembra", "female", B1);
        insertPalabra(database, "genio", "genius", B1);
        insertPalabra(database, "fantasma", "ghost", B1);
        insertPalabra(database, "nota, calificación", "grade", B1);
        insertPalabra(database, "adivinar", "guess", B1);
        insertPalabra(database, "tratar", "handle", B1);
        insertPalabra(database, "salir", "hang out", B1);
        insertPalabra(database, "escuchar", "hear", B1);
        insertPalabra(database, "al principio", "initially", B1);
        insertPalabra(database, "instrucciones", "instructions", B1);
        insertPalabra(database, "inteligencia", "intelligence", B1);
        insertPalabra(database, "rompecabezas", "jigsaw", B1);
        insertPalabra(database, "lógico", "logical", B1);
        insertPalabra(database, "arreglárselas", "manage", B1);
        insertPalabra(database, "nota, calificación", "mark", B1);
        insertPalabra(database, "matemático", "mathematical", B1);
        insertPalabra(database, "memorable", "memorable", B1);
        insertPalabra(database, "memorizar", "memorise", B1);
        insertPalabra(database, "motivar", "motivate", B1);
        insertPalabra(database, "movimiento", "movement", B1);
        insertPalabra(database, "músculo", "muscle", B1);
        insertPalabra(database, "cuaderno", "notebook", B1);
        insertPalabra(database, "obligación", "obligation", B1);
        insertPalabra(database, "demasiado", "over-", B1);
        insertPalabra(database, "superar", "overcome", B1);
        insertPalabra(database, "oxígeno", "oxygen", B1);
        insertPalabra(database, "fotógrafo", "photographer", B1);
        insertPalabra(database, "trozo", "piece", B1);
        insertPalabra(database, "psicólogo", "psychologist", B1);
        insertPalabra(database, "rompecabezas", "puzzle", B1);
        insertPalabra(database, "reconocer", "recognise", B1);
        insertPalabra(database, "recordar", "remember", B1);
        insertPalabra(database, "despistado", "scatterbrained", B1);
        insertPalabra(database, "el más fuerte", "strongest", B1);
        insertPalabra(database, "éxito", "success", B1);
        insertPalabra(database, "talentoso", "talented", B1);
        insertPalabra(database, "camiseta", "T-shirt", B1);
        insertPalabra(database, "tipo", "type", B1);
        insertPalabra(database, "entender", "understand", B1);
        insertPalabra(database, "verbal", "verbal", B1);
        insertPalabra(database, "visual", "visual", B1);
        insertPalabra(database, "capacidad", "ability", B1);
        insertPalabra(database, "admirar", "admire", B1);
        insertPalabra(database, "álbum", "album", B1);
        insertPalabra(database, "convertirse", "become", B1);
        insertPalabra(database, "clarinete", "clarinet", B1);
        insertPalabra(database, "clásico", "classical", B1);
        insertPalabra(database, "color", "colour", B1);
        insertPalabra(database, "complejo", "complex", B1);
        insertPalabra(database, "estar compuesto por", "consist of", B1);
        insertPalabra(database, "recipiente", "container", B1);
        insertPalabra(database, "cortar", "cut", B1);
        insertPalabra(database, "drogas", "drugs", B1);
        insertPalabra(database, "batería", "drums", B1);
        insertPalabra(database, "guitarra eléctrica", "electric guitar", B1);
        insertPalabra(database, "envidiar", "envy", B1);
        insertPalabra(database, "igual de", "equally", B1);
        insertPalabra(database, "fragmento", "extract", B1);
        insertPalabra(database, "aficionado, fan", "fan", B1);
        insertPalabra(database, "flauta", "flute", B1);
        insertPalabra(database, "generación", "generation", B1);
        insertPalabra(database, "auriculares", "headphones", B1);
        insertPalabra(database, "equipo de alta fidelidad", "hi-fi", B1);
        insertPalabra(database, "hip hop", "hip-hop", B1);
        insertPalabra(database, "inspirar", "inspire", B1);
        insertPalabra(database, "instrumento", "instrument", B1);
        insertPalabra(database, "a nivel internacional", "internationally", B1);
        insertPalabra(database, "jazz", "jazz", B1);
        insertPalabra(database, "teclado", "keyboard", B1);
        insertPalabra(database, "bromear", "kid", B1);
        insertPalabra(database, "montones de", "loads of", B1);
        insertPalabra(database, "letra", "lyrics", B1);
        insertPalabra(database, "mayoría", "majority", B1);
        insertPalabra(database, "milagro", "miracle", B1);
        insertPalabra(database, "perdido, faltante", "missing", B1);
        insertPalabra(database, "musical", "musical", B1);
        insertPalabra(database, "instrumento musical", "musical instrument", B1);
        insertPalabra(database, "músico", "musician", B1);
        insertPalabra(database, "pintar", "paint", B1);
        insertPalabra(database, "percusionista", "percussionist", B1);
        insertPalabra(database, "reproductor musical", "personal stereo", B1);
        insertPalabra(database, "presentación", "presentation", B1);
        insertPalabra(database, "proyecto", "project", B1);
        insertPalabra(database, "grabar", "record", B1);
        insertPalabra(database, "disco", "record", B1);
        insertPalabra(database, "reggae", "reggae", B1);
        insertPalabra(database, "repasar", "revise", B1);
        insertPalabra(database, "ritmo", "rhythm", B1);
        insertPalabra(database, "romántico", "romantic", B1);
        insertPalabra(database, "saxofón", "saxophone", B1);
        insertPalabra(database, "camisa", "shirt", B1);
        insertPalabra(database, "sencillo", "single", B1);
        insertPalabra(database, "exitoso", "successful", B1);
        insertPalabra(database, "superestrella", "superstar", B1);
        insertPalabra(database, "sintetizador", "synthesiser", B1);
        insertPalabra(database, "ir de gira", "tour", B1);
        insertPalabra(database, "trompeta", "trumpet", B1);
        insertPalabra(database, "varios", "various", B1);
        insertPalabra(database, "video", "video", B1);
        insertPalabra(database, "violencia", "violence", B1);
        insertPalabra(database, "violín", "violin", B1);
        insertPalabra(database, "voz", "voice", B1);
        insertPalabra(database, "dolor", "ache", B1);
        insertPalabra(database, "antiguo", "ancient", B1);
        insertPalabra(database, "antiséptico", "antiseptic", B1);
        insertPalabra(database, "dolor de espalda", "backache", B1);
        insertPalabra(database, "calvicie", "baldness", B1);
        insertPalabra(database, "cuerpo", "body", B1);
        insertPalabra(database, "hueso", "bone", B1);
        insertPalabra(database, "frontera", "border", B1);
        insertPalabra(database, "negocio", "business", B1);
        insertPalabra(database, "dibujos animados", "cartoon", B1);
        insertPalabra(database, "seguro", "certainly", B1);
        insertPalabra(database, "controlar", "control", B1);
        insertPalabra(database, "remedio", "cure", B1);
        insertPalabra(database, "detalle", "detail", B1);
        insertPalabra(database, "morir", "die", B1);
        insertPalabra(database, "descubrir", "discover", B1);
        insertPalabra(database, "enfermedad", "disease", B1);
        insertPalabra(database, "donativo", "donation", B1);
        insertPalabra(database, "elemento", "element", B1);
        insertPalabra(database, "ingeniero", "engineer", B1);
        insertPalabra(database, "epidemia", "epidemic", B1);
        insertPalabra(database, "todo el mundo", "everyone", B1);
        insertPalabra(database, "vista", "eyesight", B1);
        insertPalabra(database, "caer", "fall", B1);
        insertPalabra(database, "hambruna", "famine", B1);
        insertPalabra(database, "librarse de", "get rid of", B1);
        insertPalabra(database, "dolor de cabeza", "headache", B1);
        insertPalabra(database, "sede", "headquarters", B1);
        insertPalabra(database, "hipopótamo", "hippopotamus", B1);
        insertPalabra(database, "enfermedad", "illness", B1);
        insertPalabra(database, "inyección", "injection", B1);
        insertPalabra(database, "herido, lesionado", "injured", B1);
        insertPalabra(database, "secuestrar", "kidnap", B1);
        insertPalabra(database, "escalera", "ladder", B1);
        insertPalabra(database, "león", "lion", B1);
        insertPalabra(database, "líquido", "liquid", B1);
        insertPalabra(database, "mezclar", "mix", B1);
        insertPalabra(database, "mezcla", "mixture", B1);
        insertPalabra(database, "monstruo", "monster", B1);
        insertPalabra(database, "ratón", "mouse", B1);
        insertPalabra(database, "noche", "night", B1);
        insertPalabra(database, "enfermero", "nurse", B1);
        insertPalabra(database, "operar", "operate", B1);
        insertPalabra(database, "dolor", "pain", B1);
        insertPalabra(database, "paciente", "patient", B1);
        insertPalabra(database, "penicilina", "penicillin", B1);
        insertPalabra(database, "física", "physics", B1);
        insertPalabra(database, "pastilla", "pill", B1);
        insertPalabra(database, "política", "politics", B1);
        insertPalabra(database, "impedir", "prevent", B1);
        insertPalabra(database, "tirar, jalar", "pull", B1);
        insertPalabra(database, "radioactivo", "radioactive", B1);
        insertPalabra(database, "radio", "radium", B1);
        insertPalabra(database, "reconocimiento", "recognition", B1);
        insertPalabra(database, "religión", "religion", B1);
        insertPalabra(database, "aplicar", "rub", B1);
        insertPalabra(database, "salario", "salary", B1);
        insertPalabra(database, "compartir", "share", B1);
        insertPalabra(database, "piel", "skin", B1);
        insertPalabra(database, "oler", "smell", B1);
        insertPalabra(database, "alguien", "someone", B1);
        insertPalabra(database, "algo", "something", B1);
        insertPalabra(database, "dolorido", "sore", B1);
        insertPalabra(database, "especializarse", "specialise", B1);
        insertPalabra(database, "dolor de estómago", "stomach ache", B1);
        insertPalabra(database, "padecer", "suffer", B1);
        insertPalabra(database, "cirujano", "surgeon", B1);
        insertPalabra(database, "garganta", "throat", B1);
        insertPalabra(database, "atar", "tie", B1);
        insertPalabra(database, "dolor de muelas", "toothache", B1);
        insertPalabra(database, "tratar", "treat", B1);
        insertPalabra(database, "vacuna", "vaccination", B1);
        insertPalabra(database, "vehículo", "vehicle", B1);
        insertPalabra(database, "vértebra", "vertebra", B1);
        insertPalabra(database, "víctima", "victim", B1);
        insertPalabra(database, "batería, pila", "battery", B1);
        insertPalabra(database, "lector de CD", "CD drive", B1);
        insertPalabra(database, "chatear", "chat", B1);
        insertPalabra(database, "sala de chat", "chat room", B1);
        insertPalabra(database, "conectar", "connect", B1);
        insertPalabra(database, "colgarse", "crash", B1);
        insertPalabra(database, "descargar", "download", B1);
        insertPalabra(database, "unidad", "drive", B1);
        insertPalabra(database, "portátil", "laptop", B1);
        insertPalabra(database, "iniciar sesión", "log on", B1);
        insertPalabra(database, "ratón", "mouse", B1);
        insertPalabra(database, "red", "net", B1);
        insertPalabra(database, "desconectado", "offline", B1);
        insertPalabra(database, "conectado", "online", B1);
        insertPalabra(database, "imprimir", "print", B1);
        insertPalabra(database, "impresora", "printer", B1);
        insertPalabra(database, "programa", "program", B1);
        insertPalabra(database, "proveedor", "provider", B1);
        insertPalabra(database, "publicar", "publish", B1);
        insertPalabra(database, "guardar", "save", B1);
        insertPalabra(database, "buscar", "search", B1);
        insertPalabra(database, "buscador", "search engine", B1);
        insertPalabra(database, "software, programa", "software", B1);
        insertPalabra(database, "navegar", "surf", B1);
        insertPalabra(database, "charla", "talk", B1);
        insertPalabra(database, "touch pad", "touch pad", B1);
        insertPalabra(database, "usuario", "user", B1);
        insertPalabra(database, "página web", "website", B1);
        insertPalabra(database, "avanzado", "advanced", B1);
        insertPalabra(database, "ambulancia", "ambulance", B1);
        insertPalabra(database, "arqueólogo", "archaeologist", B1);
        insertPalabra(database, "arqueología", "archaeology", B1);
        insertPalabra(database, "ejército", "army", B1);
        insertPalabra(database, "astrónomo", "astronomer", B1);
        insertPalabra(database, "pelota", "ball", B1);
        insertPalabra(database, "vendaje", "bandage", B1);
        insertPalabra(database, "jefe", "chief", B1);
        insertPalabra(database, "civilización", "civilisation", B1);
        insertPalabra(database, "subir", "climb", B1);
        insertPalabra(database, "cerrado", "closed", B1);
        insertPalabra(database, "cubrir", "cover", B1);
        insertPalabra(database, "llorar", "cry", B1);
        insertPalabra(database, "lechería", "dairy", B1);
        insertPalabra(database, "decorar", "decorate", B1);
        insertPalabra(database, "zambullirse", "dive", B1);
        insertPalabra(database, "existir", "exist", B1);
        insertPalabra(database, "expedición", "expedition", B1);
        insertPalabra(database, "explicación", "explanation", B1);
        insertPalabra(database, "explorador", "explorer", B1);
        insertPalabra(database, "fabuloso", "fabulous", B1);
        insertPalabra(database, "gobernador", "governor", B1);
        insertPalabra(database, "avaricia", "greed", B1);
        insertPalabra(database, "avaricioso", "greedy", B1);
        insertPalabra(database, "esconder", "hide", B1);
        insertPalabra(database, "el más alto", "highest", B1);
        insertPalabra(database, "habitar", "inhabit", B1);
        insertPalabra(database, "hacer malabarismos", "juggle", B1);
        insertPalabra(database, "rey", "king", B1);
        insertPalabra(database, "reino", "kingdom", B1);
        insertPalabra(database, "legendario", "legendary", B1);
        insertPalabra(database, "matemáticas", "Mathematics", B1);
        insertPalabra(database, "montaña", "mountain", B1);
        insertPalabra(database, "místico", "mystical", B1);
        insertPalabra(database, "mítico", "mythical", B1);
        insertPalabra(database, "hoy en día", "nowadays", B1);
        insertPalabra(database, "de vez en cuando", "occasionally", B1);
        insertPalabra(database, "océano", "ocean", B1);
        insertPalabra(database, "palacio", "palace", B1);
        insertPalabra(database, "particular", "particular", B1);
        insertPalabra(database, "pico", "peak", B1);
        insertPalabra(database, "peatón", "pedestrian", B1);
        insertPalabra(database, "filósofo", "philosopher", B1);
        insertPalabra(database, "fontanero", "plumber", B1);
        insertPalabra(database, "puro", "pure", B1);
        insertPalabra(database, "pirámide", "pyramid", B1);
        insertPalabra(database, "recepción", "reception", B1);
        insertPalabra(database, "recepcionista", "receptionist", B1);
        insertPalabra(database, "región", "region", B1);
        insertPalabra(database, "recurso", "resource", B1);
        insertPalabra(database, "gobernar", "rule", B1);
        insertPalabra(database, "gobernante", "ruler", B1);
        insertPalabra(database, "navegar", "sail", B1);
        insertPalabra(database, "barco", "ship", B1);
        insertPalabra(database, "nevado", "snowy", B1);
        insertPalabra(database, "plaza", "square", B1);
        insertPalabra(database, "tragar", "swallow", B1);
        insertPalabra(database, "templo", "temple", B1);
        insertPalabra(database, "cima", "top", B1);
        insertPalabra(database, "tradición", "tradition", B1);
        insertPalabra(database, "viajar", "travel", B1);
        insertPalabra(database, "viajero", "traveller", B1);
        insertPalabra(database, "tesoro", "treasure", B1);
        insertPalabra(database, "visitante", "visitor", B1);
        insertPalabra(database, "querer", "want", B1);
        insertPalabra(database, "mundo", "world", B1);
        insertPalabra(database, "alojamiento", "accommodation", B1);
        insertPalabra(database, "tobillo", "ankle", B1);
        insertPalabra(database, "disculparse", "apologise", B1);
        insertPalabra(database, "organizar", "arrange", B1);
        insertPalabra(database, "poco", "bit", B1);
        insertPalabra(database, "bendecir", "bless", B1);
        insertPalabra(database, "cegar", "blind", B1);
        insertPalabra(database, "romperse", "burst", B1);
        insertPalabra(database, "autobús", "bus", B1);
        insertPalabra(database, "café", "café", B1);
        insertPalabra(database, "calcular", "calculate", B1);
        insertPalabra(database, "campamento", "camp", B1);
        insertPalabra(database, "cancelar", "cancel", B1);
        insertPalabra(database, "listo", "clever", B1);
        insertPalabra(database, "comedia", "comedy", B1);
        insertPalabra(database, "complicado", "complicated", B1);
        insertPalabra(database, "tarjeta de crédito", "credit card", B1);
        insertPalabra(database, "luz", "daylight", B1);
        insertPalabra(database, "derrotar", "defeat", B1);
        insertPalabra(database, "material", "equipment", B1);
        insertPalabra(database, "exactamente", "exactly", B1);
        insertPalabra(database, "experencia", "experience", B1);
        insertPalabra(database, "explotar", "explode", B1);
        insertPalabra(database, "pie", "foot", B1);
        insertPalabra(database, "(para) siempre", "forever", B1);
        insertPalabra(database, "con talento", "gifted", B1);
        insertPalabra(database, "guía", "guidebook", B1);
        insertPalabra(database, "pajar", "haystack", B1);
        insertPalabra(database, "helado", "icy", B1);
        insertPalabra(database, "con antelación", "in advance", B1);
        insertPalabra(database, "informar", "inform", B1);
        insertPalabra(database, "inhibición", "inhibition", B1);
        insertPalabra(database, "matar", "kill", B1);
        insertPalabra(database, "pierna", "leg", B1);
        insertPalabra(database, "camión", "lorry", B1);
        insertPalabra(database, "el más afortunado", "luckiest", B1);
        insertPalabra(database, "importante", "major", B1);
        insertPalabra(database, "de poca importancia", "minor", B1);
        insertPalabra(database, "ingenuo", "naive", B1);
        insertPalabra(database, "experiencia cercana a la muerte", "near-death experience", B1);
        insertPalabra(database, "opción", "option", B1);
        insertPalabra(database, "vidrio", "pane", B1);
        insertPalabra(database, "caño", "pipe", B1);
        insertPalabra(database, "yeso", "plaster", B1);
        insertPalabra(database, "de manera positiva", "positively", B1);
        insertPalabra(database, "arco iris", "rainbow", B1);
        insertPalabra(database, "periodista", "reporter", B1);
        insertPalabra(database, "reservar", "reserve", B1);
        insertPalabra(database, "refrán", "saying", B1);
        insertPalabra(database, "brillar", "shine", B1);
        insertPalabra(database, "shock", "shock", B1);
        insertPalabra(database, "orilla", "shore", B1);
        insertPalabra(database, "lancha motora", "speedboat", B1);
        insertPalabra(database, "estampilla", "stamp", B1);
        insertPalabra(database, "piedra", "stone", B1);
        insertPalabra(database, "un golpe de", "a stroke of", B1);
        insertPalabra(database, "gafas de sol", "sunglasses", B1);
        insertPalabra(database, "no me digas que…", "surely", B1);
        insertPalabra(database, "juguete", "toy", B1);
        insertPalabra(database, "vías", "tracks", B1);
        insertPalabra(database, "tratamiento", "treatment", B1);
        insertPalabra(database, "dar vueltas", "twist", B1);
        insertPalabra(database, "sin suerte", "unlucky", B1);
        insertPalabra(database, "despertar", "wake", B1);
        insertPalabra(database, "bienvenido", "welcome", B1);
        insertPalabra(database, "efecto invernadero", "greenhouse effect", B1);
        insertPalabra(database, "accidente", "accident", B1);
        insertPalabra(database, "alcanzar, tomar", "catch", B1);
        insertPalabra(database, "correcto", "correct", B1);
        insertPalabra(database, "esperar", "hope", B1);
        insertPalabra(database, "imaginar", "imagine", B1);
        insertPalabra(database, "vida", "life", B1);
        insertPalabra(database, "estrella", "star", B1);
        insertPalabra(database, "estación", "station", B1);
        insertPalabra(database, "ganar", "win", B1);
    }

    private void loadB2() {

    }

    private void loadC1() {

    }

    /* ------------------------------------------------------------------------------------------ */
    /* ------------------------------------------------------------------------------------------ */
    /* ------------------------------------------------------------------------------------------ */
}
